<a href="https://colab.research.google.com/github/CoderZIE/pawscanai/blob/main/classification_with_an_academic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

# import os
# for dirname, _, filenames in os.walk('/kaggle/input'):
#     for filename in filenames:
#         print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All"
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [3]:
train_dataframe=pd.read_csv("train.csv")
test_dataframe=pd.read_csv("test.csv")
train_dataframe

id  Marital status  Application mode  Application order  Course  \
0          0               1                 1                  1    9238   
1          1               1                17                  1    9238   
2          2               1                17                  2    9254   
3          3               1                 1                  3    9500   
4          4               1                 1                  2    9500   
...      ...             ...               ...                ...     ...   
76513  76513               1                17                  1    9254   
76514  76514               1                 1                  6    9254   
76515  76515               5                17                  1    9085   
76516  76516               1                 1                  3    9070   
76517  76517               1                 1                  1    9773   

       Daytime/evening attendance  Previous qualification  \
0                               1                       1   
1                               1                       1   
2                               1                       1   
3                               1                       1   
4                               1                       1   
...                           ...                     ...   
76513                           1                       1   
76514                           1                       1   
76515                           1                       1   
76516                           1                       1   
76517                           1                       1   

       Previous qualification (grade)  Nacionality  Mother's qualification  \
0                               126.0            1                       1   
1                               125.0            1                      19   
2                               137.0            1                       3   
3                               131.0            1                      19   
4                               132.0            1                      19   
...                               ...          ...                     ...   
76513                           121.0            1                      19   
76514                           125.0            1                       1   
76515                           138.0            1                      37   
76516                           136.0            1                      38   
76517                           133.1            1                      19   

       ...  Curricular units 2nd sem (credited)  \
0      ...                                    0   
1      ...                                    0   
2      ...                                    0   
3      ...                                    0   
4      ...                                    0   
...    ...                                  ...   
76513  ...                                    0   
76514  ...                                    0   
76515  ...                                    0   
76516  ...                                    0   
76517  ...                                    0   

       Curricular units 2nd sem (enrolled)  \
0                                        6   
1                                        6   
2                                        6   
3                                        8   
4                                        7   
...                                    ...   
76513                                    6   
76514                                    6   
76515                                    5   
76516                                    6   
76517                                    6   

       Curricular units 2nd sem (evaluations)  \
0                                           7   
1                                           9   
2                                           0   
3                                          11   
4   

In [4]:
unique_nationalities = test_dataframe['Nacionality'].value_counts()
unique_nationalities

Nacionality
1      50719
41       106
26        37
22        36
6         33
24        13
62        11
11         9
100        8
2          8
25         7
103        7
105        7
21         3
101        3
32         2
109        2
14         1
Name: count, dtype: int64

In [6]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.preprocessing import LabelEncoder
import matplotlib.pyplot as plt

In [7]:
# Assuming df is your DataFrame
df = train_dataframe

# Define features and target variable, excluding the 'id' column
X = df.drop(columns=['Target', 'id'])
y = df['Target']

In [8]:
# Initialize and train the Random Forest classifier
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X, y)

RandomForestClassifier(random_state=42)

In [9]:
# Make predictions on the test set
y_pred_encoded = clf.predict(X)

In [10]:
# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y, y_pred_encoded))
print("\nClassification Report:")
print(classification_report(y, y_pred_encoded))
print("\nAccuracy Score:")
print(accuracy_score(y, y_pred_encoded))

Confusion Matrix:
[[25296     0     0]
 [    0 14940     0]
 [    0     0 36282]]

Classification Report:
              precision    recall  f1-score   support

     Dropout       1.00      1.00      1.00     25296
    Enrolled       1.00      1.00      1.00     14940
    Graduate       1.00      1.00      1.00     36282

    accuracy                           1.00     76518
   macro avg       1.00      1.00      1.00     76518
weighted avg       1.00      1.00      1.00     76518


Accuracy Score:
1.0


In [11]:
# Define features for testing (assuming test dataframe doesn't have target column)
X_test = test_dataframe

X_test = X_test.drop(columns=['id'])

In [12]:
# Make predictions on the test set
y_pred = clf.predict(X_test)

In [13]:
# Add the predicted target column to the test dataframe
test_dataframe['Target'] = y_pred
test_dataframe

id  Marital status  Application mode  Application order  Course  \
0       76518               1                 1                  1    9500   
1       76519               1                 1                  1    9238   
2       76520               1                 1                  1    9238   
3       76521               1                44                  1    9147   
4       76522               1                39                  1    9670   
...       ...             ...               ...                ...     ...   
51007  127525               1                 1                  2     171   
51008  127526               2                39                  1    9119   
51009  127527               1                 1                  1     171   
51010  127528               1                 1                  3    9773   
51011  127529               1                 1                  1     171   

       Daytime/evening attendance  Previous qualification  \
0                               1                       1   
1                               1                       1   
2                               1                       1   
3                               1                      39   
4                               1                       1   
...                           ...                     ...   
51007                           1                       1   
51008                           1                      19   
51009                           1                       1   
51010                           1                       1   
51011                           1                       1   

       Previous qualification (grade)  Nacionality  Mother's qualification  \
0                               141.0            1                       3   
1                               128.0            1                       1   
2                               118.0            1                       1   
3                               130.0            1                       1   
4                               110.0            1                       1   
...                               ...          ...                     ...   
51007                           128.0            1                      38   
51008                           133.1            1                      19   
51009                           127.0            1                       1   
51010                           132.0            1                      19   
51011                           129.0            1                      37   

       ...  Curricular units 2nd sem (credited)  \
0      ...                                    0   
1      ...                                    0   
2      ...                                    0   
3      ...                                    3   
4      ...                                    0   
...    ...                                  ...   
51007  ...                                    0   
51008  ...                                    0   
51009  ...                                    0   
51010  ...                                    0   
51011  ...                                    0   

       Curricular units 2nd sem (enrolled)  \
0                                        8   
1                                        6   
2                                        6   
3                                        8   
4                                        6   
...                                    ...   
51007                                    0   
51008                                    5   
51009                                    0   
51010                                    6   
51011                                    0   

       Curricular units 2nd sem (evaluations)  \
0                                           0   
1                                           6   
2                                          11   
3                                         

In [14]:
# Select only the 'id' and 'Target' columns
filtered_df = test_dataframe[['id', 'Target']]
filtered_df

id    Target
0       76518   Dropout
1       76519  Graduate
2       76520  Graduate
3       76521  Enrolled
4       76522  Enrolled
...       ...       ...
51007  127525   Dropout
51008  127526   Dropout
51009  127527   Dropout
51010  127528   Dropout
51011  127529   Dropout

[51012 rows x 2 columns]

In [16]:
# Save the test dataframe with predicted target to a CSV file
filtered_df.to_csv('submit.csv', index=False)